title: "RStudio Learner Personas"
author: "RStudio Education Team"
email: "greg.wilson@rstudio.com"
domain: "https://rstudio-education.github.io/learner-personas/"
repo: "https://github.com/rstudio-education/learner-personas/"
repository: <USERNAME>/<PROJECT>
